### ISSUE TITLE
Rename failures are not propagated to caller of .commit()

### ISSUE THREAD

**Issue by Gunni** [andreacorbellini/rust-atomic-write-file#4]
1. make a file manually `echo foo > filename`
2. make it immutable `chattr +i filename`
3. try to write over it with this library
```
    	let mut file = AtomicWriteFile::options().open("filename")?;
	writeln!(file, "{}", contents)?;
	file.commit()?;
```
4. exit without error
5. tmp file still exists and file did not get overwritten

**Comment by Gunni** [comment]
Made a minimal test program, I got the error, I was wrong, my code must be broken somehow, nvm.

**Comment by andreacorbellini** [comment]
No problem, please feel free to report any future issue you find, thanks!
